"""
Historical-case seeder — signal-driven, aligned with Rules in App.pptx slide 2.

Populates data/historical_cases.db with ~35 past closed IE cases
spanning Sep 2025 – Mar 2026 so the C&T frontend's Previous Cases panel
has realistic reference data independent of the live simulation in
investigation.db.

Each historical case is generated by:

  1. Picking a (seller, parent_category) cluster that either matches a
     live IE investigate cluster (high-similarity), a same-seller other
     category (medium), or a neutral seller/category mix (low).

  2. Drawing the four engine signals for the case:
       VAT_Misclass = max(Engine_VAT_Ratio, Engine_ML_Watchlist) * 100
         (slide-2 "VAT Misclass" treated as a combo of the VAT test and
          the ML test — the higher of the two drives the row selection)
       VAT_Vague    = Engine_Description_Vagueness * 100
       S.R (bool)   = Engine_IE_Seller_Watchlist > 0
       $$           = VAT_Gap_Fee

  3. Applying the slide-2 decision cascade (see _decide_from_signals)
     to derive Proposed_Action_Customs + Proposed_Action_Tax + closure.

  4. Emitting 1–4 linked sales orders + 1 risk row + 1 case row.

Thresholds follow slide 2 (hard 30/70 cuts on VAT Misclass, 50 on
VAT Vague, 1 € on $$). We have some freedom on the combo formula — we
picked max() over average so a single strong signal still flags
mis-classification, matching how the table reads when VAT Misclass is
the dominant signal.

Run via seed_databases.py or directly:
    python -m lib.historical_seeder
"""
from __future__ import annotations

import random
import uuid
from datetime import datetime, timedelta, timezone

from lib.config   import HISTORICAL_CASES_DB
from lib.database import _connect, init_historical_cases_db
from lib          import vat_dataset

_RNG_SEED = 20260301
_WINDOW   = (datetime(2025, 9, 1,  tzinfo=timezone.utc),
             datetime(2026, 3, 31, tzinfo=timezone.utc))

# ── Product short-phrase pools (mirror lib/new_seeder.py, trimmed) ───────────
_PRODUCT_POOL: dict[str, list[str]] = {
    "ELECTRONICS & ACCESSORIES": [
        "Bluetooth earbuds wireless", "USB-C fast charger", "Smart plug 4-pack",
        "Wireless mouse ergonomic", "HDMI 4K switch", "Phone case magnetic",
        "Portable SSD 1TB",
    ],
    "CLOTHING & TEXTILES": [
        "Cotton t-shirt pack", "Wool sweater knit", "Sports jacket waterproof",
        "Denim slim jeans", "Silk printed scarf",
    ],
    "COSMETICS & PERSONAL CARE": [
        "Vitamin C serum 30ml", "Retinol night cream", "Mineral sunscreen SPF50",
        "Argan oil treatment", "Gentle face wash",
    ],
    "TOYS": [
        "Wooden puzzle set", "Electronic learning kit", "Building block set",
        "Plush teddy bear",
    ],
    "FOOD PRODUCTS": [
        "Dark chocolate bar", "Organic olive oil", "Manuka honey jar",
        "Pasta semolina 500g",
    ],
    "FOOD SUPPLEMENTS & VITAMINS": [
        "Vitamin D3 K2 drops", "Omega-3 fish oil", "Probiotic capsules",
        "Magnesium complex tablets",
    ],
    "BOOKS, PUBLICATIONS & DIGITAL CONTENT": [
        "Children storybook hardcover", "Art history volume", "Cookbook illustrated",
        "Digital reader subscription annual", "Educational textbook pack",
    ],
    "SPORTS & LEISURE / DIGITAL SERVICES": [
        "Yoga mat premium", "Cycling helmet pro", "Running shoes carbon",
        "Sports watch GPS",
    ],
}

# Irish canonical rate per parent category.
_CANON_RATE = {
    "ELECTRONICS & ACCESSORIES":               0.23,
    "CLOTHING & TEXTILES":                     0.23,
    "COSMETICS & PERSONAL CARE":               0.23,
    "TOYS":                                    0.23,
    "FOOD PRODUCTS":                           0.0,
    "FOOD SUPPLEMENTS & VITAMINS":             0.23,
    "BOOKS, PUBLICATIONS & DIGITAL CONTENT":   0.0,
    "SPORTS & LEISURE / DIGITAL SERVICES":     0.23,
}

# Live IE investigate clusters with per-cluster retain/release targets.
# Ordered by descending live-case risk score (observed from the new_seeder
# xlsx data) so higher-risk clusters see retain-dominant histories and
# lower-risk ones see release-dominant ones. Targets chosen so each of
# slide-1's three recommendation branches fires on at least one live case:
#   retPct > 75%   → Recommend Control
#   25%-75%        → Submit for Tax Review
#   < 25%          → Recommend Release
#
# Tuple: (seller, category, n_retain, n_release).
_HIGH_SIM_TARGETS: list[tuple[str, str, int, int]] = [
    ("Hyderabad KidsEdu Traders",   "BOOKS, PUBLICATIONS & DIGITAL CONTENT", 4, 1),  # 80% retain → retainment
    ("Chennai FoodCo Exports",      "FOOD PRODUCTS",                          3, 2),  # 60% → tax review
    ("Bengaluru ActiveGear Ltd",    "CLOTHING & TEXTILES",                    2, 3),  # 40% → tax review
    ("Mumbai TechTrade Pvt Ltd",    "ELECTRONICS & ACCESSORIES",              2, 3),  # 40% → tax review
    ("Delhi PharmaExport Pvt Ltd",  "COSMETICS & PERSONAL CARE",              1, 4),  # 20% → release
]

# Flat list kept for the summary print & backward compatibility.
_HIGH_SIM_CLUSTERS: list[tuple[str, str]] = [(s, c) for (s, c, _, _) in _HIGH_SIM_TARGETS]

_MEDIUM_SIM: list[tuple[str, str]] = [
    ("Mumbai TechTrade Pvt Ltd",    "SPORTS & LEISURE / DIGITAL SERVICES"),
    ("Hyderabad KidsEdu Traders",   "TOYS"),
    ("Delhi PharmaExport Pvt Ltd",  "FOOD SUPPLEMENTS & VITAMINS"),
    ("Bengaluru ActiveGear Ltd",    "SPORTS & LEISURE / DIGITAL SERVICES"),
    ("Chennai FoodCo Exports",      "FOOD SUPPLEMENTS & VITAMINS"),
]

_LOW_SIM: list[tuple[str, str]] = [
    ("Mumbai TechTrade Pvt Ltd",    "FOOD PRODUCTS"),
    ("Hyderabad KidsEdu Traders",   "CLOTHING & TEXTILES"),
    ("Delhi PharmaExport Pvt Ltd",  "ELECTRONICS & ACCESSORIES"),
    ("Bengaluru ActiveGear Ltd",    "COSMETICS & PERSONAL CARE"),
    ("Chennai FoodCo Exports",      "BOOKS, PUBLICATIONS & DIGITAL CONTENT"),
    ("Mumbai TechTrade Pvt Ltd",    "TOYS"),
]


# ─────────────────────────────────────────────────────────────────────────────
# Slide-2 decision tree
# ─────────────────────────────────────────────────────────────────────────────

# Profile names describe the corner of the decision table we're targeting.
_PROFILES_HIGH = [
    # Heavy retain: row 1 (high VAT-misclass, no SR) → Tax confirms risk
    "high_vat_no_sr_confirm",
    # Row 2: high VAT-misclass with SR → Tax always confirms
    "high_vat_with_sr",
    # Row 5: mid VAT-misclass, low vagueness → Tax confirms (gap > 1€)
    "mid_vat_lowvague_confirm",
]
_PROFILES_MIXED = [
    "high_vat_no_sr_confirm",    # retain
    "high_vat_no_sr_nolimited",  # row 1 with $$ ≤ 1 → Tax no/limited → release
    "mid_vat_lowvague_confirm",  # retain
    "mid_vat_lowvague_nolimited",# release (gap ≤ 1€)
    "low_vague_no_sr",           # row 7: release
]
_PROFILES_LOW = [
    "low_vague_no_sr",           # row 7: release (dominant)
    "low_clean_no_sr",           # clear release (no signals)
    "mid_vat_lowvague_nolimited",# occasional release via Tax no-limited
]

# Profiles that deterministically produce a retain outcome.
_RETAIN_PROFILES_NONZERO = ["high_vat_no_sr_confirm", "high_vat_with_sr",
                            "mid_vat_lowvague_confirm"]
# For 0%-expected categories only high_vat_with_sr reliably retains
# (the $$-gated Tax verdicts collapse to no/limited risk when gap=0).
_RETAIN_PROFILES_ZERO    = ["high_vat_with_sr"]
# Profiles that deterministically produce a release outcome.
_RELEASE_PROFILES        = ["low_vague_no_sr", "low_clean_no_sr",
                            "mid_vat_lowvague_nolimited"]


def _decide_from_signals(vat_misclass: float, vague: float,
                         sr: bool, vat_gap: float) -> tuple[str, str, str]:
    """Apply slide 2's decision cascade. Returns
    (problem_type, proposed_action_customs, proposed_action_tax).

    Problem type mirrors the case-type column on slide 2:
      "VAT Misclassification" when VAT Misclass ≥ 30
      "VAT Vague" otherwise
    Cases that land on "Request 3rd Party" are resolved post-factum
    (see _resolve_3rd_party) since historical cases must be closed.
    """
    if vat_misclass > 70:
        # Row 1 / Row 2
        problem = "VAT Misclassification"
        customs = "tax_review"
        if sr:
            tax = "risk_confirmed"                     # row 2
        else:
            tax = "risk_confirmed" if vat_gap > 1.0 else "no_limited_risk"  # row 1
        return problem, customs, tax

    if 30 <= vat_misclass <= 70:
        # Rows 3, 4, 5
        problem = "VAT Misclassification"
        if vague > 50 and not sr:
            return problem, "input_requested", ""     # row 3
        if vague > 50 and sr:
            return problem, "tax_review", "input_requested"  # row 4 — AI uncertain → 3rd party
        # row 5: low vagueness → Tax decides on $$
        tax = "risk_confirmed" if vat_gap > 1.0 else "no_limited_risk"
        return problem, "tax_review", tax

    # VAT Misclass < 30
    if vague > 50:
        problem = "VAT Vague"
        if sr:
            return problem, "tax_review", "input_requested"  # row 6 — AI uncertain
        return problem, "release", ""                         # row 7
    # No signals firing at all → auto-release path (not in table explicitly
    # but follows from the Risk Engine >80 / <30 / 30-80 guide).
    return "No Risk", "release", ""


def _resolve_3rd_party(rng: random.Random, problem: str,
                       vat_misclass: float, vague: float, sr: bool,
                       vat_gap: float) -> tuple[str, str]:
    """Historical cases are closed, so a Request 3rd Party branch must
    be followed through to its eventual resolution. We model the 3rd
    party coming back with evidence: seller-risk cases almost always
    close retain; clean cases tilt release."""
    if sr:
        return ("retainment", "risk_confirmed")
    if vat_misclass >= 30 and vat_gap > 1.0:
        return ("retainment", "risk_confirmed")
    return ("release", "no_limited_risk")


# ─────────────────────────────────────────────────────────────────────────────
# Signal drawing
# ─────────────────────────────────────────────────────────────────────────────

def _draw_signals(rng: random.Random, profile: str) -> dict:
    """Produce a dict with the four engine signals + derived VAT_Misclass."""
    if profile == "high_vat_no_sr_confirm":
        vat_r = rng.uniform(0.50, 0.90)
        ml    = rng.uniform(0.40, 0.85)
        vague = rng.uniform(0.02, 0.20)
        sr    = 0.0
        gap_h = "above"
    elif profile == "high_vat_no_sr_nolimited":
        vat_r = rng.uniform(0.50, 0.90)
        ml    = rng.uniform(0.40, 0.75)
        vague = rng.uniform(0.02, 0.20)
        sr    = 0.0
        gap_h = "below"
    elif profile == "high_vat_with_sr":
        vat_r = rng.uniform(0.45, 0.85)
        ml    = rng.uniform(0.60, 0.95)
        vague = rng.uniform(0.05, 0.30)
        sr    = rng.uniform(0.70, 1.0)
        gap_h = rng.choice(["above", "below"])
    elif profile == "mid_vat_lowvague_confirm":
        vat_r = rng.uniform(0.35, 0.65)
        ml    = rng.uniform(0.30, 0.65)
        vague = rng.uniform(0.02, 0.40)
        sr    = 0.0
        gap_h = "above"
    elif profile == "mid_vat_lowvague_nolimited":
        vat_r = rng.uniform(0.30, 0.50)
        ml    = rng.uniform(0.25, 0.50)
        vague = rng.uniform(0.02, 0.40)
        sr    = 0.0
        gap_h = "below"
    elif profile == "low_vague_no_sr":
        vat_r = rng.uniform(0.00, 0.20)
        ml    = rng.uniform(0.00, 0.25)
        vague = rng.uniform(0.55, 0.85)
        sr    = 0.0
        gap_h = "below"
    elif profile == "low_clean_no_sr":
        vat_r = rng.uniform(0.00, 0.15)
        ml    = rng.uniform(0.00, 0.15)
        vague = rng.uniform(0.02, 0.30)
        sr    = 0.0
        gap_h = "below"
    else:
        raise ValueError(f"Unknown profile: {profile}")

    vat_misclass = max(vat_r, ml) * 100.0   # slide-2 combo rule
    return {
        "engine_vat_ratio":   round(vat_r, 3),
        "engine_ml":          round(ml, 3),
        "engine_vague":       round(vague, 3),
        "engine_ie_seller":   round(sr, 3),
        "vat_misclass":       round(vat_misclass, 1),
        "gap_hint":           gap_h,
    }


_VALUE_CAP = 149.99   # stay strictly below the €150 IOSS threshold
_CLUSTER_LO = 0.894   # ±11% window → max/min ≤ 1.25 between any two orders
_CLUSTER_HI = 1.118


def _cluster_base_for_gap_hint(rng: random.Random, hint: str, applied: float,
                               expected: float, n_orders: int) -> float:
    """Pick a *case-level* base product value so the per-order values —
    each drawn within ±11% of this base — produce a total VAT gap that
    matches the hint ("above" > 1€, "below" ≤ 1€). A shared base keeps
    every order inside the case within 25% of every other order, which
    is how real invoices cluster.
    """
    if applied >= expected:
        return rng.uniform(20.0, _VALUE_CAP / _CLUSTER_HI)
    delta = expected - applied
    if hint == "above":
        # Per-order gap needs headroom so n_orders × base × delta > ~1.5 €.
        floor = max(30.0, 1.5 / (n_orders * delta) + 5.0)
        return rng.uniform(floor, _VALUE_CAP / _CLUSTER_HI)
    # "below": n_orders × base × delta ≤ ~0.9 €
    ceil = max(1.5, 0.9 / (n_orders * delta))
    return rng.uniform(1.0, ceil)


def _draw_cluster_value(rng: random.Random, base: float) -> float:
    """Per-order value within ±11% of a case's cluster base, rounded to
    2dp and capped strictly below €150."""
    v = rng.uniform(base * _CLUSTER_LO, base * _CLUSTER_HI)
    return round(min(v, _VALUE_CAP), 2)


# ─────────────────────────────────────────────────────────────────────────────
# Case assembly
# ─────────────────────────────────────────────────────────────────────────────

def _pick_seller_origin(seller_name: str) -> str:
    s = vat_dataset.seller_by_name(seller_name)
    return s["origin"] if s else "IN"


def _rand_ts(rng: random.Random) -> str:
    span = int((_WINDOW[1] - _WINDOW[0]).total_seconds())
    dt = _WINDOW[0] + timedelta(seconds=rng.randint(0, span))
    return dt.replace(microsecond=0).isoformat()


def _new_case_id(rng: random.Random) -> str:
    return f"CASE-H-{uuid.UUID(int=rng.getrandbits(128)).hex[:10].upper()}"


def _new_so_bk(rng: random.Random) -> str:
    return f"SOH-{uuid.UUID(int=rng.getrandbits(128)).hex[:12].upper()}"


def _customs_action_to_status(customs_action: str, tax_action: str) -> str:
    """Historical cases must close. Terminal customs_action maps to the
    Closed status; 'tax_review' cases close once Tax has responded."""
    return "Closed"


def _final_customs_action(rng: random.Random, problem: str,
                          customs: str, tax: str,
                          vat_misclass: float, vague: float,
                          sr: bool, vat_gap: float) -> tuple[str, str]:
    """Collapse the slide-2 cascade into the single Proposed_Action_Customs
    value stored on the closed case. Tax feedback determines the final
    customs stance when the path went through tax_review; 3rd-party paths
    resolve via _resolve_3rd_party."""
    if customs == "release":
        return ("release", tax)
    if customs == "input_requested":
        # Historical closure after 3rd-party input
        return _resolve_3rd_party(rng, problem, vat_misclass, vague, sr, vat_gap)
    # customs == "tax_review"
    if tax == "risk_confirmed":
        return ("retainment", "risk_confirmed")
    if tax == "no_limited_risk":
        return ("release", "no_limited_risk")
    if tax == "input_requested":
        return _resolve_3rd_party(rng, problem, vat_misclass, vague, sr, vat_gap)
    # No tax verdict — default to customs own call, lean retain if any signal.
    if vat_misclass >= 30 or sr:
        return ("retainment", "")
    return ("release", "")


def _build_case(rng: random.Random, seller_name: str, parent_cat: str,
                profile: str) -> dict:
    seller      = vat_dataset.seller_by_name(seller_name)
    origin      = seller["origin"] if seller else "IN"
    destination = "IE"
    pool        = _PRODUCT_POOL.get(parent_cat) or ["imported goods assorted"]
    expected    = _CANON_RATE.get(parent_cat, 0.23)

    sig = _draw_signals(rng, profile)
    sr_bool = sig["engine_ie_seller"] > 0

    # Rate misclassification: mid/high VAT-misclass profiles mis-declare,
    # low-vague profiles declare the right rate.
    if profile.startswith(("high_vat", "mid_vat")):
        tier_below = {0.23: 0.09, 0.09: 0.0}.get(expected, 0.0)
        applied = tier_below
    else:
        applied = expected

    # Pick per-order value matching the $$ hint.
    n_orders = rng.randint(1, 4)
    ts_case  = _rand_ts(rng)
    case_id  = _new_case_id(rng)
    so_bk    = _new_so_bk(rng)

    # Shared base value per case — every order's value drawn within ±11%
    # so any two orders inside the case differ by at most 25%.
    cluster_base = _cluster_base_for_gap_hint(rng, sig["gap_hint"], applied,
                                              expected, n_orders)

    orders = []
    total_value = 0.0
    total_gap   = 0.0
    for i in range(n_orders):
        v = _draw_cluster_value(rng, cluster_base)
        per_order_vat  = round(v * applied, 2)
        per_order_gap  = round(v * (expected - applied), 2)
        total_value   += v
        total_gap     += per_order_gap
        phrase = rng.choice(pool) if sig["engine_vague"] < 0.5 else f"Assorted {parent_cat.split()[0].lower()} items"
        phrase_full = f"{phrase} unit {i + 1:03d}"
        so_bk_i = so_bk if i == 0 else _new_so_bk(rng)
        orders.append({
            "Sales_Order_ID":           f"SO-HIS-{case_id[-6:]}-{i+1:02d}",
            "Sales_Order_Business_Key": so_bk_i,
            "HS_Product_Category":      parent_cat,
            "Product_Description":      phrase_full,
            "Product_Value":            v,
            "VAT_Rate":                 applied,
            "VAT_Fee":                  per_order_vat,
            "Seller_Name":              seller_name,
            "Country_Origin":           origin,
            "Country_Destination":      destination,
            "Status":                   "Closed",
            "Update_time":              ts_case,
            "Updated_by":               "historical_seed",
            "Case_ID":                  case_id,
        })

    # Resolve slide-2 path → final Customs / Tax actions.
    problem, customs_path, tax_path = _decide_from_signals(
        sig["vat_misclass"], sig["engine_vague"] * 100.0,
        sr_bool, total_gap,
    )
    final_customs, final_tax = _final_customs_action(
        rng, problem, customs_path, tax_path,
        sig["vat_misclass"], sig["engine_vague"] * 100.0, sr_bool, total_gap,
    )
    final_customs_norm = "retain" if final_customs == "retainment" else "release" if final_customs == "release" else final_customs

    # Overall case risk score: broad heuristic used by the Risk Engine
    # band on slide 2 (>80 Retain / 30-80 Investigate / <30 Release).
    #   weighted combo — mirrors ENGINE_WEIGHTS proportions in api.py
    #   without re-importing to keep this module pure.
    contribs = (
        0.50 * sig["engine_vat_ratio"]
        + 0.90 * sig["engine_ml"]
        + 1.00 * sig["engine_ie_seller"]
        + 0.80 * sig["engine_vague"]
    )
    overall = round(min(1.0, contribs / 3.2), 3)
    level = "High" if overall >= 0.80 else "Medium" if overall >= 1/3 else "Low"

    risk_row = {
        "Sales_Order_Risk_ID":         f"SOR-HIS-{case_id[-6:]}",
        "Sales_Order_Business_Key":    so_bk,
        "Risk_Type":                   "VAT",
        "Overall_Risk_Score":          overall,
        "Overall_Risk_Level":          level,
        "Seller_Risk_Score":           round(sig["engine_ml"] * 100, 1),
        "Country_Risk_Score":          0.0,
        "Product_Category_Risk_Score": 0.0,
        "Manufacturer_Risk_Score":     0.0,
        "Confidence_Score":            round(rng.uniform(0.75, 1.0), 3),
        "Overall_Risk_Description":    problem,
        "Proposed_Risk_Action":        "investigate",
        "Risk_Comment":                None,
        "Evaluation_by":               "historical_seed",
        "Update_time":                 ts_case,
        "Updated_by":                  "historical_seed",
    }

    ai = (f"Past investigation for {seller_name} on {parent_cat} imports to IE. "
          f"VAT Misclass score {sig['vat_misclass']:.0f}/100, vagueness "
          f"{sig['engine_vague']*100:.0f}/100, seller watchlist "
          f"{'yes' if sr_bool else 'no'}. Declared rate "
          f"{applied*100:.0f}% vs expected {expected*100:.0f}%. "
          f"Slide-2 path → Customs: {customs_path or 'n/a'}, Tax: "
          f"{tax_path or 'n/a'} → closed {final_customs_norm}.")

    case_row = {
        "Case_ID":                          case_id,
        "Sales_Order_Business_Key":         so_bk,
        "Status":                           "Closed",
        "VAT_Problem_Type":                 problem,
        "Recommended_Product_Value":        None,
        "Recommended_VAT_Product_Category": parent_cat,
        "Recommended_VAT_Rate":             expected,
        "Recommended_VAT_Fee":              round(total_value * expected, 2),
        "AI_Analysis":                      ai,
        "AI_Confidence":                    round(rng.uniform(0.6, 0.95), 3),
        "VAT_Gap_Fee":                      round(total_gap, 2),
        "Evaluation_by":                    "Customs Officer",
        "Proposed_Action_Tax":              final_tax or None,
        "Proposed_Action_Customs":          final_customs_norm,
        "Communication":                    "[]",
        "Additional_Evidence":              None,
        "Update_time":                      ts_case,
        "Updated_by":                       "historical_seed",
        "Created_time":                     ts_case,
        "Overall_Case_Risk_Score":          overall,
        "Overall_Case_Risk_Level":          level,
        "Engine_VAT_Ratio":                 sig["engine_vat_ratio"],
        "Engine_ML_Watchlist":              sig["engine_ml"],
        "Engine_IE_Seller_Watchlist":       sig["engine_ie_seller"],
        "Engine_Description_Vagueness":     sig["engine_vague"],
    }
    return {"orders": orders, "risk": risk_row, "case": case_row}


def _insert_case(conn, case: dict) -> None:
    for o in case["orders"]:
        conn.execute(
            "INSERT INTO Sales_Order "
            "(Sales_Order_ID, Sales_Order_Business_Key, HS_Product_Category, "
            " Product_Description, Product_Value, VAT_Rate, VAT_Fee, Seller_Name, "
            " Country_Origin, Country_Destination, Status, Update_time, Updated_by, Case_ID) "
            "VALUES "
            "(:Sales_Order_ID, :Sales_Order_Business_Key, :HS_Product_Category, "
            " :Product_Description, :Product_Value, :VAT_Rate, :VAT_Fee, :Seller_Name, "
            " :Country_Origin, :Country_Destination, :Status, :Update_time, :Updated_by, :Case_ID)",
            o,
        )
    conn.execute(
        "INSERT INTO Sales_Order_Risk "
        "(Sales_Order_Risk_ID, Sales_Order_Business_Key, Risk_Type, Overall_Risk_Score, "
        " Overall_Risk_Level, Seller_Risk_Score, Country_Risk_Score, Product_Category_Risk_Score, "
        " Manufacturer_Risk_Score, Confidence_Score, Overall_Risk_Description, Proposed_Risk_Action, "
        " Risk_Comment, Evaluation_by, Update_time, Updated_by) "
        "VALUES "
        "(:Sales_Order_Risk_ID, :Sales_Order_Business_Key, :Risk_Type, :Overall_Risk_Score, "
        " :Overall_Risk_Level, :Seller_Risk_Score, :Country_Risk_Score, :Product_Category_Risk_Score, "
        " :Manufacturer_Risk_Score, :Confidence_Score, :Overall_Risk_Description, :Proposed_Risk_Action, "
        " :Risk_Comment, :Evaluation_by, :Update_time, :Updated_by)",
        case["risk"],
    )
    conn.execute(
        "INSERT INTO Sales_Order_Case ("
        " Case_ID, Sales_Order_Business_Key, Status, VAT_Problem_Type, "
        " Recommended_Product_Value, Recommended_VAT_Product_Category, "
        " Recommended_VAT_Rate, Recommended_VAT_Fee, AI_Analysis, AI_Confidence, "
        " VAT_Gap_Fee, Evaluation_by, Proposed_Action_Tax, Proposed_Action_Customs, "
        " Communication, Additional_Evidence, Update_time, Updated_by, Created_time, "
        " Overall_Case_Risk_Score, Overall_Case_Risk_Level, Engine_VAT_Ratio, "
        " Engine_ML_Watchlist, Engine_IE_Seller_Watchlist, Engine_Description_Vagueness) "
        "VALUES ("
        " :Case_ID, :Sales_Order_Business_Key, :Status, :VAT_Problem_Type, "
        " :Recommended_Product_Value, :Recommended_VAT_Product_Category, "
        " :Recommended_VAT_Rate, :Recommended_VAT_Fee, :AI_Analysis, :AI_Confidence, "
        " :VAT_Gap_Fee, :Evaluation_by, :Proposed_Action_Tax, :Proposed_Action_Customs, "
        " :Communication, :Additional_Evidence, :Update_time, :Updated_by, :Created_time, "
        " :Overall_Case_Risk_Score, :Overall_Case_Risk_Level, :Engine_VAT_Ratio, "
        " :Engine_ML_Watchlist, :Engine_IE_Seller_Watchlist, :Engine_Description_Vagueness)",
        case["case"],
    )


def seed_historical_cases_db() -> int:
    init_historical_cases_db()
    rng = random.Random(_RNG_SEED)

    conn = _connect(HISTORICAL_CASES_DB)
    with conn:
        conn.execute("DELETE FROM Sales_Order_Case")
        conn.execute("DELETE FROM Sales_Order_Risk")
        conn.execute("DELETE FROM Sales_Order")
    conn.close()

    cases: list[dict] = []

    # High-similarity: live IE investigate clusters. Each cluster has
    # an explicit (n_retain, n_release) target so slide-1's three
    # recommendation branches are exercised across the live cases:
    # higher-risk clusters get retain-dominant histories, lower-risk
    # ones get release-dominant ones.
    for seller, cat, n_retain, n_release in _HIGH_SIM_TARGETS:
        zero_rate      = _CANON_RATE.get(cat, 0.23) == 0.0
        retain_pool    = _RETAIN_PROFILES_ZERO if zero_rate else _RETAIN_PROFILES_NONZERO
        for _ in range(n_retain):
            cases.append(_build_case(rng, seller, cat, rng.choice(retain_pool)))
        for _ in range(n_release):
            cases.append(_build_case(rng, seller, cat, rng.choice(_RELEASE_PROFILES)))

    # Medium: mixed profiles, same sellers but different categories.
    for seller, cat in _MEDIUM_SIM:
        profile = rng.choice(_PROFILES_MIXED)
        cases.append(_build_case(rng, seller, cat, profile))

    # Low: release-dominant profiles, unusual (seller, cat) combos.
    for seller, cat in _LOW_SIM:
        profile = rng.choice(_PROFILES_LOW)
        cases.append(_build_case(rng, seller, cat, profile))

    rng.shuffle(cases)

    conn = _connect(HISTORICAL_CASES_DB)
    with conn:
        for c in cases:
            _insert_case(conn, c)
    conn.close()

    from collections import Counter
    by_action  = Counter(c["case"]["Proposed_Action_Customs"] for c in cases)
    by_problem = Counter(c["case"]["VAT_Problem_Type"] for c in cases)
    by_cluster = Counter((c["orders"][0]["Seller_Name"], c["orders"][0]["HS_Product_Category"])
                         for c in cases)
    print(f"  {len(cases)} historical cases written")
    print(f"  outcomes: {dict(by_action)}")
    print(f"  problem types: {dict(by_problem)}")
    print(f"  top 5 (seller, cat) clusters:")
    for (s, cat), n in by_cluster.most_common(5):
        print(f"    {n}× {s[:24]:<24} / {cat}")

    return len(cases)


if __name__ == "__main__":
    n = seed_historical_cases_db()
    print(f"\n✓ {n} historical cases in {HISTORICAL_CASES_DB}")
